name: MailRocket

on:
  push:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  compile_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/.crates.toml
            ~/.cargo/.crates2.json
            ~/.cargo/bin
            ~/.cargo/registry
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Update rust
        run: |
          rustup update
          cargo --version
          rustc --version

      - name: Add dependencies (to manifest file)
        run: |
          cargo add actix-web
          cargo add tokio --features "macros rt-multi-thread"

      - name: Compile project (and check dependencies for errors)
        run: cargo check

      - name: Run integration tests
        run: cargo test --test *